### ISSUE TITLE
Display Y Axis rage, 'control' line and grid lines.

### ISSUE THREAD

**Issue by udyandutta** [PredixDev/px-simple-bar-chart#8]
Hello,

3 quick questions / possible feature requests. 

1. Is it possible to display data range on the Y axis ?
2. Is it possible to show a control line over the entire chart ( representing something like target/control or expected behavior) ?
3. Is it possible to display grid lines in the background ?

Please refer to attached screenshot for more info. 

Thanks,
Udyan

![px-simple-bar-chart](https://cloud.githubusercontent.com/assets/18316512/18446920/3e68b51e-78d9-11e6-8efd-f89413361bcf.png)

**Comment by ek** [comment]
Hi @udyandutta ,

Thank you for the excellent feature recommendations!

Unfortunately I don't think it's likely they will land in this component. The px-simple-bar-chart is named appropriately because it is designed to be very simple, with a minimum of features.

I suggest that you and/or your team fork the repo and add the features you need yourself. The changes you propose should be quite straightforward.

Best regards,
Eric
